version: '3.8'

services:
  data-collector:
    build:
      context: .
      dockerfile: docker/data-collector.dockerfile
    container_name: nautilus-data-collector
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./src:/app/src
      - ./main.py:/app/main.py
      - ./.env:/app/.env
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
